### ISSUE TITLE
[Feature request] Dealing with folders

### ISSUE THREAD

**Issue by vinaybedre** [SBoudrias/mem-fs-editor#123]
Hi,

Yeoman uses mem-fs-editor, and I see no support for operations related to folders. Eg. Creating of a folder or Copying of a folder is not supported by mem-fs-editor. It would be a nice to have feature. 
See a question posted on stackoverflow https://stackoverflow.com/questions/29830927/creating-empty-directories-in-a-yeoman-generator

Can you guys work on this?

**Comment by SBoudrias** [comment]
Similar to git, the internal system of mem-fs only tracks files. This is by design and unlikely to change. The main reason is that even is `mem-fs-editor` was to copy empty folders; it wouldn't work with git. So people would run into issue where they wonder why their empty folder doesn't gets created (because it wasn't part of their package) or why they disappear when their colleagues clone their newly created project.

If the solution on StackOverflow doesn't work for you, another workaround you have is to add empty files like `.gitkeep` in those folders you want to make part of your boilerplate (that's the only way they'll be kept inside of your git repo anyway)

**Comment by vinaybedre** [comment]
Thanks for adding context of git and yes, you are absolutely correct. I will close the incident.
