### ISSUE TITLE
Copy fails when filepath has special characters

### ISSUE THREAD

**Issue by ventsyv** [SBoudrias/mem-fs-editor#134]
I'm getting an error when I try to copy a file with special characters in it. For example, something like: `/path/something/.hidden/myFile.txt (test) `

I'm working on a test to confirm the problem.

**Comment by sinedied** [comment]
Adding more context, as this is an issue without workaround in the latest version:
- previously using `globOptions: { noext: true }` worked as a workaround for special chars
- but now, even using `globOptions: { extglob: false }` and escaping special chars with `\\` do not work, because of the `globify` util that will force a glob when the file does not exists, and it can't find one because of the special chars.

Any ideas?

**Comment by SBoudrias** [comment]
You can now rely on the `noGlob` option :)
