### ISSUE TITLE
Deleting files using `memFsEditor.delete` causes an error as of NodeJS v16

### ISSUE THREAD

**Issue by manuth** [SBoudrias/mem-fs-editor#177]
Calling `memFsEditor.delete` on a file-path (instead of a directory-path) causes an issue in most recent NodeJS-versions.
https://github.com/nodejs/node/blob/master/doc/api/fs.md#fspromisesrmdirpath-options

As seen in this piece of code, you're using `rmdir` for files, which is meant to be used for directories.
https://github.com/SBoudrias/mem-fs-editor/blob/fec287c254a462f8f58246ca0a52f8d564d8df40/lib/actions/commit-file-async.js#L26-L28

You might want to use `fs-extra.remove` instead.

**Comment by mshima** [comment]
There is no need for the additional dependency.

It was renamed to `rm` https://nodejs.org/api/fs.html#fs_fspromises_rm_path_options at v14.14.0.
If the problem is `on a path that is a file is no longer permitted and results in an ENOENT error on Windows and an ENOTDIR error on POSIX.`.
You should add exception handling.

Test if rm exists and fallback to rmdir otherwise.

**Comment by manuth** [comment]
@mshima Thanks for your input!
I just created another PR (#179) which takes your remarks into account.
Are you allowed to merge PRs and publish new versions?

**Comment by SBoudrias** [comment]
9.0.1 is out with the fix. And CI now covers Node 16 which will ensure future support.
