### ISSUE TITLE
copyTpl not skipping files.

### ISSUE THREAD

**Issue by hemanth** [SBoudrias/mem-fs-editor#45]
```js
this.fs.copyTpl([
  this.templatePath() + '/**',
  '!**/cli.js'
], this.destinationPath(), tpl);
```
`!**/cli,js` is not respected.

More info at [nm](https://github.com/sindresorhus/generator-nm/issues/20) 

Ref issue -> [generator-834](https://github.com/yeoman/generator/issues/834)

**Comment by gaboesquivel** [comment]
it turned out to be related to isaacs/node-blog  https://github.com/gaboesquivel/node-glob/commit/619267d0a331db20d26e3bd24e60cfcaa194d0df 
I have to write a test for this and then I'll PR.

**Comment by hemanth** [comment]
@gaboesquivel Sweet :+1:

**Comment by gaboesquivel** [comment]
@SBoudrias @sindresorhus @hemanth 
It seems that negation is deprecated, in node-glob, in favor of an explicit ignore array option.
[isaacs/node-glob/blob/master/test/negation-test.js#L28](https://github.com/isaacs/node-glob/blob/master/test/negation-test.js#L28)

I could a add a test case there that covers .dot the problem.. in this case negation doesn't work because the templates are inside .nvm  ... [node-glob negation skips dotfiles](https://github.com/gaboesquivel/node-glob/commit/619267d0a331db20d26e3bd24e60cfcaa194d0df) 
 
However I guess that is not what we want... instead [sindresorhus/globby](https://github.com/sindresorhus/globby) should accept the ignores option and/or accept negation patterns and pass them as ignore array to glob

**Comment by SBoudrias** [comment]
I'm okay with switching to globby if that's what we want. Want to send a PR going this way?

**Comment by sindresorhus** [comment]
Globby accepts ignore patterns and converts them to the glob ignore option.

**Comment by gaboesquivel** [comment]
hmm, I guess the ignore option in glob has the same flaw which would make sense... will check

**Comment by gaboesquivel** [comment]
waiting on https://github.com/isaacs/node-glob/pull/227,  already tested and it fixes the problem

**Comment by hemanth** [comment]
@gaboesquivel Looks like that is merged.

**Comment by sindresorhus** [comment]
@SBoudrias This can be closed.

**Comment by SBoudrias** [comment]
Awesome, thanks all!

**Comment by hemanth** [comment]
:+1:
