### ISSUE TITLE
Would be nice if copy supported copying in-memory folders

### ISSUE THREAD

**Issue by binduwavell** [SBoudrias/mem-fs-editor#50]
I have the following in memory but not on disk:
```
/path/to/file1.txt
/path/to/file2.txt
```

I would like to perform:
```javascript
this.copy('/path/to', '/new/path/to');
```

So that I end up with:
```
/path/to/file1.txt
/path/to/file2.txt
/new/path/to/file1.txt
/new/path/to/file2.txt
```

Currently this fail with:
```
Trying to copy from a source that does not exist: /path/to
```

Interestingly if ```/path/to``` exists in the physical filesystem, I think this works (has been a couple days so this needs double checking.) @SBoudrias suggested the following workaround, which does work perfectly even when the files are only in memory:

```javascript
this.copy('/path/to/**', '/new/path/to');
```

**Comment by binduwavell** [comment]
```javascript
this.copy('/path/to/**', '/new/path/to');
```

Is not failing, but I'm uncertain it's performing the desired copy operation...

**Comment by blai** [comment]
@binduwavell can you please describe `this.copy('/path/to/**', '/new/path/to');`'s behavior?

**Comment by SBoudrias** [comment]
@binduwavell mem-fs only handles files. Folder handling is kind of tricky as it is not really a file and it's hard to distinguish between a file without extension and a proper folder.

FWIW, `git` itself doesn't handle empty folders at all. The usual workaround is to add a marker file inside these empty directories (usually called `.gitkeep`).

I think I'll close this issue as there's the `.gitkeep` file workaround and because even if you could copy empty directories with mem-fs-editor, you won't be able to keep any empty directory in a git project - which mean you'd probably be blocked from copying empty directories by lower level system tools.
